name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: cd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC"
      - run: dir
      - run: cd "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC"
      - run: dir
